### ISSUE TITLE
"docker build . -t mqbadge:latest" gives error

### ISSUE THREAD

**Issue by ashutoshmate** [ibm-messaging/mq-dev-badge-sample#8]
Step 14/17 : RUN echo app:passw0rd | chpasswd
 ---> Running in 90de31bb8561
**chpasswd: line 1: user 'app' does not exist
chpasswd: error detected, changes ignored**
The command '/bin/sh -c echo app:passw0rd | chpasswd' returned a non-zero code: 1

**Comment by chughts** [comment]
This is because of changes to the ibmcom/mq docker image. As explained in the following stack overflow answer.

https://stackoverflow.com/questions/61373195/ibmcom-mq-docker-image-backward-compatibility-issue/62192274#62192274

Short term fix would be to modify line 32 of the docker file, which is currently

````
FROM ibmcom/mq:latest
````

to
````
FROM ibmcom/mq:9.1.4.0-r1
````

Long term the docker file should be modified to use htpasswd to create the app user. The way the password is set up would also change.

**Comment by chughts** [comment]
The docker file and the ticket app have been fixed to work with the current FROM ibmcom/mq:latest

Which means that it won't now work with ibmcom/mq:9.1.4.0-r1 or earlier.
